#!/usr/bin/env python3
"""Generate golden pre-tokenization vectors for the byte-level BPE splitter.

The tokenizer's pre-tokenizer must split text byte-identically to the reference
(llama.cpp / HF `tokenizers`, which copy these regexes verbatim from each
model's `tokenizer.json`). To prove that without a network dependency at test
time, we run the *exact same documented patterns* through Python's `regex`
module — a regex engine entirely independent of Rust's `fancy-regex` — over a
tricky corpus, and vendor the `(input -> chunks)` pairs as a Rust fixture. The
Rust test then asserts its splitter reproduces them.

Dependency: the `regex` PyPI module (`pip install regex`); the stdlib `re` does
not support `\\p{L}` or inline `(?i:...)` groups.

Usage:  python3 scripts/gen_pretokenize_golden.py > tests/fixtures/pretokenize_golden.rs
"""

import sys

try:
    import regex
except ImportError:
    sys.exit("this script needs the `regex` module: pip install regex")

# Patterns must stay byte-identical to the PRE_* constants in src/tokenizer.rs.
PATTERNS = {
    "gpt-2": r"'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+",
    "llama-bpe": r"(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\r\n\p{L}\p{N}]?\p{L}+|\p{N}{1,3}| ?[^\s\p{L}\p{N}]+[\r\n]*|\s*[\r\n]+|\s+(?!\S)|\s+",
    "qwen2": r"(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\r\n\p{L}\p{N}]?\p{L}+|\p{N}| ?[^\s\p{L}\p{N}]+[\r\n]*|\s*[\r\n]+|\s+(?!\S)|\s+",
}

# A corpus exercising the tricky cases called out in the backlog: contractions
# (incl. uppercase, which only the case-insensitive patterns fold), digit runs
# (the clearest discriminator between the three patterns), CJK, emoji (incl. a
# skin-tone modifier and a ZWJ sequence), accents, leading/trailing spaces,
# tabs, and newlines (LF, CRLF, runs).
CORPUS = [
    "",
    "hello world",
    "Hello World",
    " leading",
    "  two leading",
    "trailing ",
    "trailing   ",
    "it's a test, isn't it? I'd've thought so.",
    "IT'S HE'LL THEY'RE WE'VE you'd",
    "'tis o'clock",
    "the year 2024 and 007 and 1234567",
    "mix3d w0rds and 100,000.50",
    "a1b2c3 ABC123def",
    "你好世界，这是一个测试。",
    "日本語のテキスト 123",
    "한국어 텍스트",
    "café naïve résumé",
    "emoji 😀 🎉 done",
    "skin 👍🏽 tone",
    "family 👨‍👩‍👧‍👦 zwj",
    "symbols #@$%^&* end",
    "https://example.com/p?q=1&x=2",
    "snake_case kebab-case",
    "tab\tseparated\tvalues",
    "line one\nline two",
    "crlf\r\nwindows",
    "many\n\n\nnewlines",
    "  \n \t mixed ws  ",
    "trailing newline\n",
    "   ",
    "\n",
    "\t\t",
]


def rs_str(s: str) -> str:
    """Escape `s` as a Rust string literal (UTF-8 chars kept verbatim)."""
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append("\\u{%x}" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def chunks(pattern: str, text: str):
    return [m.group(0) for m in regex.finditer(pattern, text)]


def main() -> None:
    lines = [
        "// @generated by scripts/gen_pretokenize_golden.py — do not edit by hand.",
        "//",
        "// (input, expected_chunks) per `tokenizer.ggml.pre` name. The reference",
        "// chunkings come from Python's `regex` module running the same documented",
        "// patterns — an engine independent of Rust's fancy-regex.",
        "#[rustfmt::skip]",
        "pub const PRETOKENIZE_GOLDEN: &[(&str, &[(&str, &[&str])])] = &[",
    ]
    for pre, pat in PATTERNS.items():
        lines.append(f"    ({rs_str(pre)}, &[")
        for text in CORPUS:
            cs = chunks(pat, text)
            # Sanity: the chunks must reassemble the input exactly.
            assert "".join(cs) == text, (pre, repr(text), cs)
            rendered = ", ".join(rs_str(c) for c in cs)
            lines.append(f"        ({rs_str(text)}, &[{rendered}]),")
        lines.append("    ]),")
    lines.append("];")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
