//! GBNF grammar-constrained decoding (Phase 5.1).
//!
//! Parses a [GBNF](https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md)
//! grammar and matches it against generated bytes, so a [`SamplerStage`] can mask
//! the logits to only tokens that keep the grammar satisfiable — the engine's
//! path to reliable JSON / structured output.
//!
//! [`SamplerStage`]: crate::sampler::SamplerStage
//!
//! Representation (after parsing): a grammar is a list of **rules**; each rule is
//! a list of **alternates**; each alternate is a sequence of **elements**
//! ([`Elem::Char`] matches one byte, [`Elem::Ref`] enters another rule). The
//! postfix operators `* + ?` and groups `( … )` are desugared into anonymous
//! rules at parse time, so the matcher only ever sees `Char`/`Ref`.
//!
//! Matching is the standard stack-of-cursors NFA (à la llama.cpp's
//! `llama_grammar`): the state is a set of stacks, each stack a list of cursors
//! into the grammar whose top is the next element to match. We operate on **bytes**
//! (a UTF-8 literal becomes a byte sequence; classes are byte ranges) — exact for
//! ASCII / JSON grammars; multi-byte char *ranges* are out of scope.

use std::collections::{HashMap, HashSet};

use crate::sampler::{SamplerStage, TokenDataArray};

/// A GBNF grammar for a JSON object — the target for `response_format:
/// {"type":"json_object"}`. Byte-level (ASCII) but covers standard JSON.
pub const JSON_GRAMMAR: &str = r#"
root   ::= object
value  ::= object | array | string | number | "true" | "false" | "null"
object ::= "{" ws ( string ws ":" ws value ( "," ws string ws ":" ws value )* )? ws "}"
array  ::= "[" ws ( value ( "," ws value )* )? ws "]"
string ::= "\"" ( [^"\\] | "\\" . )* "\""
number ::= "-"? ( [0-9] | [1-9] [0-9]* ) ( "." [0-9]+ )? ( [eE] [-+]? [0-9]+ )?
ws     ::= [ \t\n]*
"#;

/// A set of byte ranges (inclusive), optionally negated — one `[...]` class or a
/// single literal byte (a singleton range).
#[derive(Clone, Debug, PartialEq)]
pub struct CharSet {
    ranges: Vec<(u8, u8)>,
    negate: bool,
}

impl CharSet {
    fn single(b: u8) -> Self {
        CharSet { ranges: vec![(b, b)], negate: false }
    }

    fn matches(&self, b: u8) -> bool {
        let hit = self.ranges.iter().any(|&(lo, hi)| lo <= b && b <= hi);
        hit != self.negate
    }
}

/// One element of an alternate's sequence.
#[derive(Clone, Debug, PartialEq)]
pub enum Elem {
    /// Match exactly one byte from the set.
    Char(CharSet),
    /// Enter rule `usize` (its alternates), returning here when one completes.
    Ref(usize),
}

/// A parsed GBNF grammar: `rules[r]` is rule `r`'s alternates, each a sequence of
/// [`Elem`]s. `root` is the entry rule.
#[derive(Clone, Debug)]
pub struct Grammar {
    rules: Vec<Vec<Vec<Elem>>>,
    root: usize,
}

/// A cursor: element `idx` of `rules[rule][alt]`.
type Cursor = (usize, usize, usize);
/// A parse stack; the last cursor is active, earlier ones are return points.
type Stack = Vec<Cursor>;

impl Grammar {
    /// Parse a GBNF grammar. Requires a `root` rule.
    pub fn parse(src: &str) -> Result<Grammar, String> {
        Parser::new(src).parse()
    }

    /// The initial match state (the closure of the root rule's alternates).
    fn start(&self) -> Vec<Stack> {
        let mut state = Vec::new();
        for alt in 0..self.rules[self.root].len() {
            self.close(vec![(self.root, alt, 0)], &mut state);
        }
        dedup(&mut state);
        state
    }

    /// ε-closure of `stack`: expand it (and its forks) until every resulting stack
    /// sits on a `Char` terminal or is empty (a complete parse), pushing those into
    /// `out`. A `Ref` forks a stack per referenced alternate; a completed alternate
    /// pops and advances its caller past the `Ref`. A worklist with a visited-set of
    /// whole stacks makes this a terminating fixpoint — a grammar cycle re-derives
    /// an already-seen stack and stops (so left-recursion can't loop forever).
    fn close(&self, stack: Stack, out: &mut Vec<Stack>) {
        let mut seen: HashSet<Stack> = HashSet::new();
        let mut work = vec![stack];
        while let Some(s) = work.pop() {
            if !seen.insert(s.clone()) {
                continue;
            }
            let Some(&(r, a, d)) = s.last() else {
                out.push(s); // empty stack = accepting (complete)
                continue;
            };
            if d >= self.rules[r][a].len() {
                // Alternate complete: pop, advance the caller past its `Ref`.
                let mut s2 = s;
                s2.pop();
                if let Some(top) = s2.last_mut() {
                    top.2 += 1;
                }
                work.push(s2);
                continue;
            }
            match &self.rules[r][a][d] {
                Elem::Char(_) => out.push(s), // terminal — wait for a byte
                Elem::Ref(rr) => {
                    let rr = *rr;
                    for alt in 0..self.rules[rr].len() {
                        let mut s2 = s.clone();
                        s2.push((rr, alt, 0));
                        work.push(s2);
                    }
                }
            }
        }
    }

    /// Whether any stack is empty — the grammar is fully satisfied (EOS allowed).
    fn is_accepting(state: &[Stack]) -> bool {
        state.iter().any(|s| s.is_empty())
    }

    /// Advance the state by one byte; returns the new set of stacks (empty if `b`
    /// is rejected by every stack).
    fn advance(&self, state: &[Stack], b: u8) -> Vec<Stack> {
        let mut next = Vec::new();
        for s in state {
            let Some(&(r, a, d)) = s.last() else { continue };
            if let Elem::Char(cs) = &self.rules[r][a][d] {
                if cs.matches(b) {
                    let mut s2 = s.clone();
                    s2.last_mut().unwrap().2 += 1;
                    self.close(s2, &mut next);
                }
            }
        }
        dedup(&mut next);
        next
    }

    /// Advance through a whole byte string; `None` if the grammar rejects it part
    /// way (used to test a candidate token without committing).
    fn advance_bytes(&self, state: &[Stack], bytes: &[u8]) -> Option<Vec<Stack>> {
        let mut cur = state.to_vec();
        for &b in bytes {
            cur = self.advance(&cur, b);
            if cur.is_empty() {
                return None;
            }
        }
        Some(cur)
    }
}

/// A [`SamplerStage`] that constrains decoding to a [`Grammar`]: it masks every
/// candidate whose token bytes can't extend the grammar (and the EOG tokens
/// until the grammar is satisfied), then advances the parse state on the accepted
/// token. Place it at the front of the chain so the truncation stages see only
/// grammar-valid candidates.
pub struct GrammarStage {
    grammar: Grammar,
    state: Vec<Stack>,
    pieces: std::sync::Arc<Vec<Vec<u8>>>,
    eog: Vec<u32>,
}

impl GrammarStage {
    /// `pieces[id]` is token `id`'s output bytes (`Tokenizer::token_piece`),
    /// shared (`Arc`) so a server can reuse one table across requests; `eog`
    /// lists end-of-generation token ids (allowed only once the grammar is in an
    /// accepting state, so a constrained run can still stop).
    pub fn new(grammar: Grammar, pieces: std::sync::Arc<Vec<Vec<u8>>>, eog: Vec<u32>) -> Self {
        let state = grammar.start();
        GrammarStage { grammar, state, pieces, eog }
    }

    /// Build a stage from GBNF source + a tokenizer, computing the shared piece
    /// table from the vocab. (A server should build the piece table once and call
    /// [`GrammarStage::new`] per request instead.)
    pub fn from_source(src: &str, tokenizer: &crate::tokenizer::Tokenizer) -> Result<Self, String> {
        let grammar = Grammar::parse(src)?;
        let pieces = std::sync::Arc::new(
            (0..tokenizer.vocab_size())
                .map(|i| tokenizer.token_piece(i))
                .collect::<Vec<_>>(),
        );
        Ok(GrammarStage::new(grammar, pieces, tokenizer.eog_ids()))
    }
}

impl SamplerStage for GrammarStage {
    fn apply(&mut self, cur: &mut TokenDataArray) {
        let accepting = Grammar::is_accepting(&self.state);
        for c in cur.data[..cur.size].iter_mut() {
            let allowed = if self.eog.contains(&c.id) {
                accepting
            } else {
                match self.pieces.get(c.id as usize) {
                    Some(p) if !p.is_empty() => self.grammar.advance_bytes(&self.state, p).is_some(),
                    _ => false,
                }
            };
            if !allowed {
                c.logit = f32::NEG_INFINITY;
            }
        }
    }

    fn accept(&mut self, token: u32) {
        if self.eog.contains(&token) {
            return;
        }
        if let Some(p) = self.pieces.get(token as usize) {
            if let Some(next) = self.grammar.advance_bytes(&self.state, p) {
                self.state = next;
            }
        }
    }

    fn reset(&mut self) {
        self.state = self.grammar.start();
    }

    fn name(&self) -> &'static str {
        "grammar"
    }
}

fn dedup(stacks: &mut Vec<Stack>) {
    stacks.sort();
    stacks.dedup();
}

// ---------------------------------------------------------------------------
// Parser.
// ---------------------------------------------------------------------------

struct Parser<'a> {
    src: &'a [u8],
    pos: usize,
    rules: Vec<Vec<Vec<Elem>>>,
    names: HashMap<String, usize>,
}

impl<'a> Parser<'a> {
    fn new(src: &'a str) -> Self {
        Parser { src: src.as_bytes(), pos: 0, rules: Vec::new(), names: HashMap::new() }
    }

    fn parse(mut self) -> Result<Grammar, String> {
        // Pass 1: assign an id to every named rule (refs may be forward).
        self.scan_names()?;
        self.rules = vec![Vec::new(); self.names.len()];
        // Pass 2: parse each rule body.
        self.pos = 0;
        loop {
            self.skip_ws();
            if self.pos >= self.src.len() {
                break;
            }
            let name = self.ident().ok_or("expected a rule name")?;
            self.skip_ws();
            if !self.eat("::=") {
                return Err(format!("expected '::=' after rule '{name}'"));
            }
            let id = self.names[&name];
            let alts = self.parse_alternates()?;
            self.rules[id] = alts;
        }
        let root = *self.names.get("root").ok_or("grammar has no 'root' rule")?;
        Ok(Grammar { rules: self.rules, root })
    }

    /// First pass: find `name ::=` rule headers and number them.
    fn scan_names(&mut self) -> Result<(), String> {
        let mut next = 0;
        loop {
            self.skip_ws();
            if self.pos >= self.src.len() {
                break;
            }
            let name = self.ident().ok_or("expected a rule name")?;
            self.skip_ws();
            if !self.eat("::=") {
                return Err(format!("expected '::=' after rule '{name}'"));
            }
            self.names.entry(name).or_insert_with(|| {
                let id = next;
                next += 1;
                id
            });
            self.skip_to_next_rule();
        }
        Ok(())
    }

    /// Advance to just before the next `name ::=` header (or EOF), skipping a
    /// rule body without parsing it (used only in the name-scan pass).
    fn skip_to_next_rule(&mut self) {
        loop {
            self.skip_ws();
            if self.pos >= self.src.len() {
                return;
            }
            // A rule header is an identifier immediately followed (after ws) by ::=.
            let save = self.pos;
            if let Some(_name) = self.ident() {
                let after = self.pos;
                self.skip_ws();
                if self.eat("::=") {
                    self.pos = save; // leave the header for the body pass
                    return;
                }
                self.pos = after; // a rule-ref inside the body; keep scanning
            } else {
                // Skip one element (string/class/punctuation/byte).
                self.skip_element();
            }
        }
    }

    fn skip_element(&mut self) {
        match self.peek() {
            Some(b'"') => {
                let _ = self.string_literal();
            }
            Some(b'[') => {
                let _ = self.char_class();
            }
            _ => self.pos += 1,
        }
    }

    fn parse_alternates(&mut self) -> Result<Vec<Vec<Elem>>, String> {
        let mut alts = vec![self.parse_sequence()?];
        loop {
            self.skip_ws();
            if self.eat("|") {
                alts.push(self.parse_sequence()?);
            } else {
                break;
            }
        }
        Ok(alts)
    }

    fn parse_sequence(&mut self) -> Result<Vec<Elem>, String> {
        let mut seq = Vec::new();
        loop {
            self.skip_ws();
            match self.peek() {
                None => break,
                Some(b'|') | Some(b')') => break,
                // Stop at the next rule header (`ident ::=`).
                Some(c) if is_ident_start(c) => {
                    let save = self.pos;
                    let name = self.ident().unwrap();
                    let after = self.pos;
                    self.skip_ws();
                    if self.eat("::=") {
                        self.pos = save; // next rule — leave it
                        break;
                    }
                    self.pos = after;
                    let id = *self
                        .names
                        .get(&name)
                        .ok_or_else(|| format!("reference to undefined rule '{name}'"))?;
                    seq.extend(self.apply_postfix(vec![Elem::Ref(id)]));
                }
                Some(b'"') => {
                    let bytes = self.string_literal()?;
                    let base: Vec<Elem> = bytes.into_iter().map(|b| Elem::Char(CharSet::single(b))).collect();
                    seq.extend(self.apply_postfix(base));
                }
                Some(b'[') => {
                    let cs = self.char_class()?;
                    seq.extend(self.apply_postfix(vec![Elem::Char(cs)]));
                }
                Some(b'(') => {
                    self.pos += 1;
                    let alts = self.parse_alternates()?;
                    self.skip_ws();
                    if !self.eat(")") {
                        return Err("expected ')'".into());
                    }
                    let id = self.add_rule(alts);
                    seq.extend(self.apply_postfix(vec![Elem::Ref(id)]));
                }
                Some(b'.') => {
                    self.pos += 1;
                    let any = CharSet { ranges: vec![(0, 255)], negate: false };
                    seq.extend(self.apply_postfix(vec![Elem::Char(any)]));
                }
                Some(c) => return Err(format!("unexpected character '{}'", c as char)),
            }
        }
        Ok(seq)
    }

    /// Wrap `base` per a trailing `*`/`+`/`?` by adding an anonymous rule.
    fn apply_postfix(&mut self, base: Vec<Elem>) -> Vec<Elem> {
        match self.peek() {
            Some(b'*') => {
                self.pos += 1;
                // R ::= base R | ε
                let id = self.reserve_rule();
                let mut rec = base.clone();
                rec.push(Elem::Ref(id));
                self.rules[id] = vec![rec, vec![]];
                vec![Elem::Ref(id)]
            }
            Some(b'+') => {
                self.pos += 1;
                // R ::= base R | base
                let id = self.reserve_rule();
                let mut rec = base.clone();
                rec.push(Elem::Ref(id));
                self.rules[id] = vec![rec, base];
                vec![Elem::Ref(id)]
            }
            Some(b'?') => {
                self.pos += 1;
                // R ::= base | ε
                let id = self.add_rule(vec![base, vec![]]);
                vec![Elem::Ref(id)]
            }
            _ => base,
        }
    }

    fn add_rule(&mut self, alts: Vec<Vec<Elem>>) -> usize {
        let id = self.rules.len();
        self.rules.push(alts);
        id
    }

    fn reserve_rule(&mut self) -> usize {
        let id = self.rules.len();
        self.rules.push(Vec::new());
        id
    }

    // --- lexing helpers ---

    fn peek(&self) -> Option<u8> {
        self.src.get(self.pos).copied()
    }

    fn skip_ws(&mut self) {
        while let Some(c) = self.peek() {
            if c == b'#' {
                while let Some(c) = self.peek() {
                    self.pos += 1;
                    if c == b'\n' {
                        break;
                    }
                }
            } else if c.is_ascii_whitespace() {
                self.pos += 1;
            } else {
                break;
            }
        }
    }

    fn eat(&mut self, s: &str) -> bool {
        if self.src[self.pos..].starts_with(s.as_bytes()) {
            self.pos += s.len();
            true
        } else {
            false
        }
    }

    fn ident(&mut self) -> Option<String> {
        let start = self.pos;
        if !self.peek().is_some_and(is_ident_start) {
            return None;
        }
        while self.peek().is_some_and(|c| is_ident_start(c) || c.is_ascii_digit()) {
            self.pos += 1;
        }
        Some(String::from_utf8_lossy(&self.src[start..self.pos]).into_owned())
    }

    /// Parse a `"..."` literal into its raw bytes (handling escapes).
    fn string_literal(&mut self) -> Result<Vec<u8>, String> {
        self.pos += 1; // opening quote
        let mut out = Vec::new();
        loop {
            match self.peek() {
                None => return Err("unterminated string literal".into()),
                Some(b'"') => {
                    self.pos += 1;
                    return Ok(out);
                }
                Some(b'\\') => {
                    self.pos += 1;
                    out.extend(self.escape()?);
                }
                Some(c) => {
                    self.pos += 1;
                    out.push(c);
                }
            }
        }
    }

    /// Parse a `[...]` char class into a [`CharSet`].
    fn char_class(&mut self) -> Result<CharSet, String> {
        self.pos += 1; // '['
        let negate = self.peek() == Some(b'^');
        if negate {
            self.pos += 1;
        }
        let mut ranges = Vec::new();
        loop {
            match self.peek() {
                None => return Err("unterminated char class".into()),
                Some(b']') => {
                    self.pos += 1;
                    return Ok(CharSet { ranges, negate });
                }
                _ => {
                    let lo = self.class_byte()?;
                    // A range `a-z` (but a trailing '-' before ']' is a literal).
                    if self.peek() == Some(b'-') && self.src.get(self.pos + 1) != Some(&b']') {
                        self.pos += 1;
                        let hi = self.class_byte()?;
                        ranges.push((lo.min(hi), lo.max(hi)));
                    } else {
                        ranges.push((lo, lo));
                    }
                }
            }
        }
    }

    /// One byte inside a class (handles escapes).
    fn class_byte(&mut self) -> Result<u8, String> {
        match self.peek() {
            Some(b'\\') => {
                self.pos += 1;
                let e = self.escape()?;
                e.into_iter()
                    .next()
                    .ok_or_else(|| "empty escape in class".to_string())
            }
            Some(c) => {
                self.pos += 1;
                Ok(c)
            }
            None => Err("unterminated char class".into()),
        }
    }

    /// Decode an escape sequence (after the `\`) to its bytes.
    fn escape(&mut self) -> Result<Vec<u8>, String> {
        let c = self.peek().ok_or("dangling escape")?;
        self.pos += 1;
        Ok(match c {
            b'n' => vec![b'\n'],
            b'r' => vec![b'\r'],
            b't' => vec![b'\t'],
            b'x' => {
                let hi = self.hex_digit()?;
                let lo = self.hex_digit()?;
                vec![hi * 16 + lo]
            }
            other => vec![other], // \\ \" \[ \] \- \/ etc. — literal
        })
    }

    fn hex_digit(&mut self) -> Result<u8, String> {
        let c = self.peek().ok_or("expected hex digit")?;
        let v = (c as char).to_digit(16).ok_or("invalid hex digit")? as u8;
        self.pos += 1;
        Ok(v)
    }
}

fn is_ident_start(c: u8) -> bool {
    c.is_ascii_alphabetic() || c == b'_' || c == b'-'
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Does `g` accept the whole string (and end in an accepting state)?
    fn accepts(g: &Grammar, s: &str) -> bool {
        match g.advance_bytes(&g.start(), s.as_bytes()) {
            Some(state) => Grammar::is_accepting(&state),
            None => false,
        }
    }

    #[test]
    fn literal_alternation() {
        let g = Grammar::parse(r#"root ::= "yes" | "no""#).unwrap();
        assert!(accepts(&g, "yes"));
        assert!(accepts(&g, "no"));
        assert!(!accepts(&g, "maybe"));
        assert!(!accepts(&g, "ye")); // incomplete
    }

    #[test]
    fn char_classes_and_ranges() {
        let g = Grammar::parse("root ::= [a-c] [0-9]").unwrap();
        assert!(accepts(&g, "a0"));
        assert!(accepts(&g, "c9"));
        assert!(!accepts(&g, "d0"));
        assert!(!accepts(&g, "a")); // needs the digit too
    }

    #[test]
    fn negated_class() {
        let g = Grammar::parse(r#"root ::= "\"" [^"]* "\"""#).unwrap();
        assert!(accepts(&g, "\"abc\""));
        assert!(accepts(&g, "\"\"")); // empty contents
        assert!(!accepts(&g, "\"ab")); // unterminated
    }

    #[test]
    fn star_plus_optional() {
        let star = Grammar::parse("root ::= [a]*").unwrap();
        assert!(accepts(&star, ""));
        assert!(accepts(&star, "aaa"));
        let plus = Grammar::parse("root ::= [a]+").unwrap();
        assert!(!accepts(&plus, ""));
        assert!(accepts(&plus, "aa"));
        let opt = Grammar::parse(r#"root ::= "-"? [0-9]"#).unwrap();
        assert!(accepts(&opt, "5"));
        assert!(accepts(&opt, "-5"));
        assert!(!accepts(&opt, "--5"));
    }

    #[test]
    fn rule_refs_and_groups() {
        let g = Grammar::parse(
            r#"
            root ::= obj
            obj ::= "{" pair ("," pair)* "}"
            pair ::= [a-z]+ "=" [0-9]+
            "#,
        )
        .unwrap();
        assert!(accepts(&g, "{a=1}"));
        assert!(accepts(&g, "{ab=12,c=3}"));
        assert!(!accepts(&g, "{a=1,}"));
        assert!(!accepts(&g, "{}"));
    }

    #[test]
    fn advance_and_accepting_track_state() {
        let g = Grammar::parse(r#"root ::= "ab""#).unwrap();
        let s0 = g.start();
        assert!(!Grammar::is_accepting(&s0));
        assert!(g.advance(&s0, b'b').is_empty()); // 'b' not allowed first
        let s1 = g.advance(&s0, b'a');
        assert!(!s1.is_empty());
        let s2 = g.advance(&s1, b'b');
        assert!(Grammar::is_accepting(&s2));
        assert!(g.advance(&s2, b'c').is_empty());
    }

    #[test]
    fn rejects_grammar_without_root() {
        assert!(Grammar::parse("foo ::= \"x\"").is_err());
    }

    #[test]
    fn grammar_stage_masks_and_allows_eog_when_complete() {
        use crate::sampler::{SamplerStage, TokenData, TokenDataArray};
        let arr = || TokenDataArray {
            data: (0..4).map(|i| TokenData { id: i, logit: 0.0, p: 0.0 }).collect(),
            size: 4,
            selected: None,
            sorted: false,
        };
        // Tokens: 0="a", 1="b", 2="c", 3 = EOG (empty piece).
        let g = Grammar::parse(r#"root ::= "ab""#).unwrap();
        let pieces = std::sync::Arc::new(vec![b"a".to_vec(), b"b".to_vec(), b"c".to_vec(), Vec::new()]);
        let mut stage = GrammarStage::new(g, pieces, vec![3]);

        let mut cur = arr();
        stage.apply(&mut cur);
        assert!(cur.data[0].logit.is_finite()); // "a" valid first
        assert_eq!(cur.data[1].logit, f32::NEG_INFINITY); // "b" not yet
        assert_eq!(cur.data[2].logit, f32::NEG_INFINITY); // "c" never
        assert_eq!(cur.data[3].logit, f32::NEG_INFINITY); // EOG not yet (incomplete)

        stage.accept(0); // consume "a"
        let mut cur = arr();
        stage.apply(&mut cur);
        assert_eq!(cur.data[0].logit, f32::NEG_INFINITY);
        assert!(cur.data[1].logit.is_finite()); // only "b" now

        stage.accept(1); // consume "b" → grammar complete
        let mut cur = arr();
        stage.apply(&mut cur);
        assert!(cur.data[3].logit.is_finite()); // EOG allowed (accepting)
        assert_eq!(cur.data[0].logit, f32::NEG_INFINITY); // no more chars
    }

    #[test]
    fn json_grammar_accepts_objects() {
        let g = Grammar::parse(JSON_GRAMMAR).unwrap();
        assert!(accepts(&g, "{}"));
        assert!(accepts(&g, r#"{"a":1}"#));
        assert!(accepts(&g, r#"{"x":[1,2,3],"y":"hi","z":true}"#));
        assert!(accepts(&g, r#"{"n":-1.5e3}"#));
        assert!(!accepts(&g, "{"));
        assert!(!accepts(&g, "[1,2]")); // root is an object
        assert!(!accepts(&g, r#"{"a":}"#));
    }
}
